### ISSUE TITLE
希望设置文件在ShortCutHelper.exe同级目录下

### ISSUE THREAD

**Issue by lingchuanbo** [liuzhengdong2/ShortCutHelper#1]
1.考虑绿色方便携带，在config.json添加个参数0和1，0为默认位置，1为同级目录！
2.快捷键自定义设置

**Comment by liuzhengdong2** [comment]
> 1.考虑绿色方便携带，在config.json添加个参数0和1，0为默认位置，1为同级目录！
> 2.快捷键自定义设置

@lingchuanbo 第一个问题下一版就解决，第二个问题可能得再等等，最近在主要在加快捷键，同时主体功能已经开发完了，所以开发速度会降低。

**Comment by liuzhengdong2** [comment]
@lingchuanbo 现在你可以把config文件直接转移到exe文件目录然后软件会自动切换为绿色模式。
