### ISSUE TITLE
匹配增加窗口类名Class

### ISSUE THREAD

**Issue by lingchuanbo** [liuzhengdong2/ShortCutHelper#3]
你好！因为有些程序名未显示窗口中，导致未正确显示，希望在匹配窗口的时候 能增加支持窗口类！

**Comment by liuzhengdong2** [comment]
这不捐点钱？🙃

**Comment by lingchuanbo** [comment]
可以呀 但顺带多提个建议，根据内容多少，自适应大小！

**Comment by liuzhengdong2** [comment]
@lingchuanbo 目前采用滚动条的方式来扩展内容，然后显示逻辑还在考虑要不要一个分类另起一行。

**Comment by liuzhengdong2** [comment]
@lingchuanbo 目前支持**应用名**和**窗口标题**两种匹配方式，基本上类名会和应用名重合，能提供一下此情况之外的应用吗？

**Comment by lingchuanbo** [comment]
虚幻5
界面是这样的
https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimg.3dmgame.com%2Fuploads%2Fimages%2Fnews%2F20210530%2F1622385831_804906.jpg&refer=http%3A%2F%2Fimg.3dmgame.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1627999034&t=fc3e0016c366e800a66da75acf290791

Mr.Ling




liu zhengdong ***@***.***> 于2021年7月4日周日 下午9:50写道：

**Comment by lingchuanbo** [comment]
自适应 觉得cheatkeys 还可以
https://cheatkeys.com/

**Comment by liuzhengdong2** [comment]
图片这里我显示不全，同时展示以下我这边条目过多的情形，你也可以自己测试一下。
![图片](https://tuchuang-liuzhengdong.oss-cn-shanghai.aliyuncs.com/image/xiaobai/0~_$RT0Z]G4CBXQ0WB)9D75.png)

**Comment by lingchuanbo** [comment]
![image](https://user-images.githubusercontent.com/4213515/124391026-19b6c600-dd21-11eb-9698-7c8f2cac5a89.png)
你可以看下，我用应用名字也是一样不显示！

**Comment by liuzhengdong2** [comment]
@lingchuanbo 了解了，回头测试一下

**Comment by liuzhengdong2** [comment]
@lingchuanbo 下了虚幻引擎试了，应用名为UE4Editor 以任务管理器显示为准。

**Comment by lingchuanbo** [comment]
![image](https://user-images.githubusercontent.com/4213515/124402082-5fdf4a00-dd60-11eb-9aa7-6e8f345196ab.png)
不对
任务管理器显示的是UnrealEditor.exe,但UnrealEditor为名还是错的

**Comment by liuzhengdong2** [comment]
@lingchuanbo 已下载虚幻5引擎，测试应用名为unrealeditor，修改文件后需要重启应用。

**Comment by lingchuanbo** [comment]
可以了 谢谢~~那这种情况下 需要怎么去找这个正确应用名呢

**Comment by liuzhengdong2** [comment]
@lingchuanbo 任务管理器即可。
